# Summarize results of questions
```{r}
library(tidytable)
library(stringr)
library(ggplot2)
library(readxl)

setwd("paper")

source("src/util.r")

fig_path <- "figs/"
```

## Load data
```{r}
# question info
q_df <- read_excel("../experiment/questions.xlsx")

# responses
responses_df <- list.files(
    "data/spr",
    full.names = TRUE, pattern = "responses_.*\\.csv$"
) |>
    lapply(read_multiple_sessions_csv) |>
    bind_rows() |>
    filter(document_id < 10) |> # filter out practice texts
    arrange(participant_number, document_id) |>
    left_join(
        q_df |>
            select(document_id, question_id, `Type of question`),
        by = c("document_id", "question_id")
    ) |>
    rename("type" = `Type of question`) |>
    mutate(
        "document_id" = as.factor(document_id),
        "type" = factor(type, levels = c("Local", "Bridging", "Global"))
    )
```

## Familiarity
```{r}
responses_df |>
    filter(question_id == 0) |> # zero is familiarity
    mutate("response" = as.numeric(response)) |>
    # group_by(document_id, story_name) |>
    summarize(
        "mean_familiarity" = mean(response),
        "sd" = sd(response),
        "max" = max(response),
        "min" = min(response),
        "N" = n()
    )
```

```{r}
responses_df |>
    filter(question_id == 0) |> # zero is familiarity
    mutate("response" = as.numeric(response)) |>
    group_by(document_id, story_name) |>
    mutate(
        "mean_familiarity" = mean(response),
        "sd" = sd(response),
        "N" = n(),
    ) |>
    ggplot(aes(x = document_id, y = response)) +
    geom_bar(stat = "summary", fun = "mean", fill = "lightblue2") +
    geom_errorbar(
        aes(
            ymin = mean_familiarity - sd,
            ymax = mean_familiarity + sd
        ),
        width = .5
    ) +
    theme_minimal() +
    labs(
        x = "ID",
        y = "Familiarity Response"
    )
```

```{r}
responses_df |>
    filter(question_id == 0) |> # zero is familiarity
    mutate("response" = as.factor(response)) |>
    count(document_id, response, name = "count") |>
    group_by(document_id) |>
    mutate("percent" = count / sum(count)) |>
    ungroup() |>
    complete(document_id, response, fill = list(count = 0, percent = 0)) |>
    ggplot(aes(x = document_id, y = percent, fill = response)) +
    geom_col(
        position = position_dodge(preserve = "single"),
        width = 0.7, color = "black"
    ) +
    theme_minimal() +
    scale_fill_manual(
        values = c(
            "#d8f3fc", "lightblue1", "lightblue2",
            "lightblue3", "lightblue4"
        )
    ) +
    geom_text(aes(label = count),
        position = position_dodge(width = .7),
        vjust = -0.5, size = 2.5
    ) +
    scale_y_continuous(limits = c(0, 1.05)) + # Set y-axis to 110%
    labs(
        x = "Document ID",
        y = "",
        fill = "Response"
    ) +
    theme(legend.position = "bottom")

ggsave(paste(fig_path, "familiarity_prop.pdf", sep = ""), height = 3, width = 7)
```

## Comprehenion
Percent correct by participant_number
```{r}
responses_df |>
    filter(question_id > 0) |> # zero is familiarity
    group_by(participant_number) |>
    summarize(
        "n_comprehension_correct" = sum(correct),
        "percent_comprehension_correct" = mean(correct),
        "sd" = sd(correct)
    ) |>
    ungroup() |>
    summarize(
        "mean_comprehension_correct" = mean(n_comprehension_correct),
        "mean_percent_correct" = mean(percent_comprehension_correct),
        "sd" = sd(percent_comprehension_correct),
        "max" = max(percent_comprehension_correct),
        "min" = min(percent_comprehension_correct)
    )
```

```{r}
responses_df |>
    filter(question_id > 0) |> # zero is familiarity
    group_by(participant_number) |>
    summarize(
        "n_comprehension_correct" = sum(correct),
        "percent_comprehension_correct" = mean(correct),
        "sd" = sd(correct)
    ) |>
    ggplot(aes(x = percent_comprehension_correct)) +
    geom_histogram(fill = "aliceblue", color = "black") +
    geom_vline(
        aes(xintercept = mean(percent_comprehension_correct)),
        linetype = "dashed"
    ) +
    theme_minimal() +
    labs(
        x = "Percent Correct",
        y = ""
    )
```

Percent correct by document_id
```{r}
responses_df |>
    filter(question_id > 0) |> # zero is familiarity
    group_by(document_id) |>
    summarize(
        "n_comprehension_correct" = sum(correct),
        "percent_comprehension_correct" = mean(correct),
        "sd" = sd(correct)
    )
```

Percent of correct responses of all questions
```{r}
responses_df |>
    filter(question_id > 0) |> # zero is familiarity
    group_by(document_id, question_id) |>
    summarize(
        "percent_correct" = mean(correct),
        "sd" = sd(correct)
    ) |>
    print(n = (8 * 6))

responses_df |>
    filter(question_id > 0) |> # zero is familiarity
    group_by(document_id, question_id) |>
    summarize(
        "percent_correct" = mean(correct),
        "sd" = sd(correct)
    ) |>
    ungroup() |>
    summarize(
        "min" = min(percent_correct),
        "max" = max(percent_correct)
    )
```
```{r}
responses_df |>
    filter(question_id > 0) |> # zero is familiarity
    group_by(document_id, question_id) |>
    summarize(
        "percent_correct" = mean(correct),
        "sd" = sd(correct)
    ) |>
    ungroup() |>
    mutate(
        "id" = as.factor(document_id):as.factor(question_id)
    ) |>
    ggplot(aes(x = id, y = percent_correct, color = document_id)) +
    geom_point() +
    geom_errorbar(
        aes(
            ymin = percent_correct - sd,
            ymax = percent_correct + sd
        )
    ) +
    theme_minimal() +
    scale_color_manual(
        values = c(
            "steelblue1", "slateblue1", "steelblue2", "slateblue2",
            "steelblue3", "slateblue3", "steelblue4", "slateblue4"
        )
    ) +
    theme(legend.position = "bottom") +
    labs(x = "", y = "Percent correct")
```

```{r}
responses_df |>
    filter(question_id > 0) |> # zero is familiarity
    mutate("doc_id" = paste("ID", document_id)) |>
    group_by(story_name, document_id, question_id, type) |>
    mutate(
        "proportion_correct" = mean(correct),
        "sd" = sd(correct)
    ) |>
    ungroup() |>
    mutate(
        "type" = as.factor(type),
        "question_id" = as.factor(question_id)
    ) |>
    ggplot(aes(x = question_id, y = correct, fill = type)) +
    geom_bar(stat = "summary", fun = "mean") +
    geom_errorbar(
        aes(
            ymin = proportion_correct - sd,
            ymax = proportion_correct + sd
        ),
        width = .5
    ) +
    facet_wrap(. ~ doc_id, ncol = 4) +
    theme_minimal() +
    scale_fill_manual(values = c("lightblue2", "lightblue3", "lightblue4")) +
    theme(legend.position = "bottom") +
    labs(
        x = "Question Number",
        y = "Proportion Correct",
        fill = "Question Type"
    )

ggsave(
    paste(fig_path, "comprehension_responses.pdf", sep = ""),
    height = 4, width = 7
)
```

Percent of correct responses by type (local, briding, global)
```{r}
responses_df |>
    filter(question_id > 0) |> # zero is familiarity
    group_by(document_id, type) |>
    summarize(
        "n_comprehension_correct" = sum(correct),
        "percent_comprehension_correct" = mean(correct),
        "sd" = sd(correct)
    )

responses_df |>
    filter(question_id > 0) |> # zero is familiarity
    group_by(type) |>
    summarize(
        "n_comprehension_correct" = sum(correct),
        "percent_comprehension_correct" = mean(correct),
        "sd" = sd(correct)
    )
```

```{r}
responses_df |>
    filter(question_id > 0) |> # zero is familiarity
    group_by(story_name, document_id, type) |>
    mutate(
        "percent_correct" = mean(correct),
        "sd" = sd(correct)
    ) |>
    ungroup() |>
    mutate(
        "type" = as.factor(type)
    ) |>
    ggplot(aes(x = type, y = correct, fill = type)) +
    geom_bar(stat = "summary", fun = "mean") +
    geom_errorbar(
        aes(
            ymin = percent_correct - sd,
            ymax = percent_correct + sd
        ),
        width = .5
    ) +
    facet_wrap(. ~ story_name, ncol = 2) +
    theme_minimal() +
    scale_fill_manual(
        values = c("lightblue2", "lightblue3", "lightblue4"),
        guide = "none"
    ) +
    theme(legend.position = "bottom")
```

```{r}
responses_df |>
    filter(question_id > 0) |> # zero is familiarity
    group_by(story_name, document_id, type) |>
    mutate(
        "percent_correct" = mean(correct),
        "sd" = sd(correct)
    ) |>
    ungroup() |>
    mutate(
        "type" = as.factor(type)
    ) |>
    ggplot(aes(x = type, y = correct, fill = document_id)) +
    geom_bar(position = "dodge", stat = "summary", fun = "mean") +
    geom_errorbar(
        aes(
            ymin = percent_correct - sd,
            ymax = percent_correct + sd
        ),
        position = "dodge", width = .9
    ) +
    theme_minimal() +
    scale_fill_manual(
        values = c(
            "grey70", "grey65", "grey60", "grey55",
            "grey50", "grey45", "grey40", "grey35"
        )
    ) +
    theme(legend.position = "bottom")
```

```{r}
responses_df |>
    filter(question_id > 0) |> # zero is familiarity
    group_by(type) |>
    mutate(
        "percent_correct" = mean(correct),
        "sd" = sd(correct)
    ) |>
    ungroup() |>
    mutate(
        "type" = as.factor(type)
    ) |>
    ggplot(aes(x = type, y = correct, fill = type)) +
    geom_bar(stat = "summary", fun = "mean") +
    geom_errorbar(
        aes(
            ymin = percent_correct - sd,
            ymax = percent_correct + sd
        ),
        width = .5
    ) +
    theme_minimal() +
    scale_fill_manual(
        values = c("lightblue2", "lightblue3", "lightblue4"),
        guide = "none"
    ) +
    theme(legend.position = "bottom")
```